name: Potential Bug Report
description: Typically these would be used to inform us of and track potential bugs
labels: ["bug"]
body:
  - type: checkboxes
    id: pre-checks
    attributes:
      label: My actions before raising this issue
      description: Get help fast by ensuring your issue isn't covered elsewhere
      options:
        - label: Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
          required: true
        - label: Read/searched [the docs](https://docs.openfaas.com/)
          required: true
        - label: Searched [past issues](/issues)
          required: true
  - type: dropdown
    id: sponsors
    attributes:
      label: Are you a GitHub Sponsor (Yes/No?)
      description: Issues created by customers or monthly sponsors are prioritised 
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: Tell us what should be happening.
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: Tell us what is happening instead of the expected behavior.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: What are the steps to reproduce?
      description: Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant.
    validations:
      required: true
  - type: textarea
    id: workaround
    attributes:
      label: List All Possible Solutions and Workarounds
      description: Suggest a fix/reason for the bug, or implementation ideas, or workarounds which could avoid making changes.
    validations:
      required: true
  - type: textarea
    id: recommend
    attributes:
      label: Which Solution Do You Recommend?
      description: Of the suggested solutions which would you try first? 
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Context
      description: Any additional context such as how this is affecting you or could affect other users.
    validations:
      required: true
  - type: textarea
    attributes:
      label: faas-cli version
      description: "Full output from: `faas-cli version`"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Docker version
      description: "Full output from: `docker version` (e.g. Docker 17.0.05 )"
    validations:
      required: true
  - type: dropdown
    id: openfaas-flavour
    attributes:
      label: Kubernetes or faasd?
      description: Are you using OpenFaaS on Kubernetes or [faasd](https://github.com/openfaas/faasd)?
      options:
        - "Kubernetes"
        - "faasd"
  - type: textarea
    attributes:
      label: Operating System and version
      description: "Operating System and version (e.g. Linux, Windows, MacOS)"
    validations:
      required: true
  - type: input
    attributes:
      label: Example code
      description: "link to GitHub repo or gist to reproduce problem"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other diagnostic information
      description: Logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)
    validations:
      required: true
